#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
maven_parent_dir="$DIR/../prefetch-simulation"
sim_dir="$DIR/"

function die() {
	echo "$@" >&2
	exit 1
}

id=$1

materialiser_jar=$(find "$maven_parent_dir/materialiser/target" -name materialiser-*-jar-with-dependencies.jar)
if [ -z "$materialiser_jar" ]; then
	(cd $maven_parent_dir && mvn clean package) || die "mvn clean package failed."
fi

materialiser_jar=$(find "$maven_parent_dir/materialiser/target" -name materialiser-*-jar-with-dependencies.jar)
runner_jar=$(find "$maven_parent_dir/runner/target" -name runner-*-jar-with-dependencies.jar)
painter_jar=$(find "$maven_parent_dir/painter/target" -name painter-*-jar-with-dependencies.jar)
[ -z "$materialiser_jar" ] && die "materialiser JAR not found"
[ -z "$runner_jar" ] && die "runner JAR not found"
[ -z "$painter_jar" ] && die "painter JAR not found"

[ -d "$sim_dir/$id" ] || die "simulation $id not found"
[ -f "$sim_dir/$id/configuration" ] || die "configuration for $id not found"

sim="$sim_dir/$id"

java -jar "$materialiser_jar" generate-genesis < "$sim/configuration" > "$sim/genesis" || die "generating genesis failed"
java -jar "$painter_jar" png < "$sim/genesis" > "$sim/genesis.png" || die "drawing genesis PNG failed"
java -jar "$painter_jar" eps < "$sim/genesis" > "$sim/genesis.eps" || die "drawing genesis EPS failed"
java -jar "$runner_jar" < "$sim_dir/$id/genesis"
java -jar "$painter_jar" tex-timeline < "$sim/genesis" > "$sim/genesis.eps" || die "drawing genesis EPS failed"

