#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
maven_parent_dir="$DIR/../prefetch-simulation"
sim_dir="$DIR/"

function die() {
	echo "$@" >&2
	exit 1
}

id=$1

materialiser_jar=$(find "$maven_parent_dir/materialiser/target" -name materialiser-*-jar-with-dependencies.jar)
if [ -z "$materialiser_jar" ]; then
	(cd $maven_parent_dir && mvn clean package) || die "mvn clean package failed."
fi

materialiser_jar=$(find "$maven_parent_dir/materialiser/target" -name materialiser-*-jar-with-dependencies.jar)
runner_jar=$(find "$maven_parent_dir/runner/target" -name runner-*-jar-with-dependencies.jar)
visualiser_jar=$(find "$maven_parent_dir/visualiser/target" -name visualiser-*-jar-with-dependencies.jar)
[ -z "$materialiser_jar" ] && die "materialiser JAR not found"
[ -z "$runner_jar" ] && die "runner JAR not found"
[ -z "$visualiser_jar" ] && die "visualiser JAR not found"

[ -d "$sim_dir/$id" ] || die "simulation $id not found"
[ -f "$sim_dir/$id/configuration" ] || die "configuration for $id not found"

sim="$sim_dir/$id"

java -jar "$materialiser_jar" < "$sim/configuration" > "$sim/genesis" || die "generating genesis failed"
java -jar "$visualiser_jar" tex-genesis < "$sim/genesis" > "$sim/genesis.tex" || die "drawing genesis TeX failed"
java -jar "$runner_jar" < "$sim/genesis" | tee "$sim/result-summary.txt" || die "running failed"
java -jar "$visualiser_jar" tex-timeline < "$sim/genesis" > "$sim/result-timeline.tex" || die "drawing timeline TeX failed"

function tex2pdf() {
	file="$1"
	(cd "$sim"
		pdflatex "$file" >/dev/null
		ret=$?
		rm -f *.aux *.log
		exit $ret
	) || die "pdflatex failed"
}

tex2pdf "genesis.tex"
tex2pdf "result-timeline.tex"

rm -f "$sim"/*.tex

